# Generated by Django 4.0.2 on 2022-02-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='industry',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
