# Generated by Django 4.0.2 on 2022-02-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0003_stockbj_stocksh_stocksz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockshk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('p_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ma5', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ma10', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ma20', models.DecimalField(decimal_places=3, max_digits=8)),
                ('v_ma5', models.DecimalField(decimal_places=2, max_digits=12)),
                ('v_ma10', models.DecimalField(decimal_places=2, max_digits=12)),
                ('v_ma20', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stockszc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('p_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ma5', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ma10', models.DecimalField(decimal_places=3, max_digits=8)),
                ('ma20', models.DecimalField(decimal_places=3, max_digits=8)),
                ('v_ma5', models.DecimalField(decimal_places=2, max_digits=12)),
                ('v_ma10', models.DecimalField(decimal_places=2, max_digits=12)),
                ('v_ma20', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
    ]
