# Generated by Django 4.0.2 on 2022-02-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0004_stockshk_stockszc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbj',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockbj',
            name='pre_close',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stocksh',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocksh',
            name='pre_close',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stockshk',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockshk',
            name='pre_close',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stocksz',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocksz',
            name='pre_close',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stockszc',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockszc',
            name='pre_close',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='stockbj',
            name='turnover',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stocksh',
            name='turnover',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockshk',
            name='turnover',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stocksz',
            name='turnover',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockszc',
            name='turnover',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
