# Generated by Django 4.0.2 on 2022-02-05 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0006_alter_stockbj_ma10_alter_stockbj_ma20_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbj',
            name='ma10',
        ),
        migrations.RemoveField(
            model_name='stockbj',
            name='ma20',
        ),
        migrations.RemoveField(
            model_name='stockbj',
            name='ma5',
        ),
        migrations.RemoveField(
            model_name='stockbj',
            name='v_ma10',
        ),
        migrations.RemoveField(
            model_name='stockbj',
            name='v_ma20',
        ),
        migrations.RemoveField(
            model_name='stockbj',
            name='v_ma5',
        ),
        migrations.RemoveField(
            model_name='stocksh',
            name='ma10',
        ),
        migrations.RemoveField(
            model_name='stocksh',
            name='ma20',
        ),
        migrations.RemoveField(
            model_name='stocksh',
            name='ma5',
        ),
        migrations.RemoveField(
            model_name='stocksh',
            name='v_ma10',
        ),
        migrations.RemoveField(
            model_name='stocksh',
            name='v_ma20',
        ),
        migrations.RemoveField(
            model_name='stocksh',
            name='v_ma5',
        ),
        migrations.RemoveField(
            model_name='stockshk',
            name='ma10',
        ),
        migrations.RemoveField(
            model_name='stockshk',
            name='ma20',
        ),
        migrations.RemoveField(
            model_name='stockshk',
            name='ma5',
        ),
        migrations.RemoveField(
            model_name='stockshk',
            name='v_ma10',
        ),
        migrations.RemoveField(
            model_name='stockshk',
            name='v_ma20',
        ),
        migrations.RemoveField(
            model_name='stockshk',
            name='v_ma5',
        ),
    ]
