# Generated by Django 4.0.2 on 2022-02-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0007_remove_stockbj_ma10_remove_stockbj_ma20_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbj',
            name='date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stocksh',
            name='date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stockshk',
            name='date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stocksz',
            name='date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stockszc',
            name='date',
            field=models.DateField(max_length=10),
        ),
    ]
