# Generated by Django 4.0.2 on 2022-02-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0008_alter_stockbj_date_alter_stocksh_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('open', models.DecimalField(decimal_places=2, max_digits=7)),
                ('high', models.DecimalField(decimal_places=2, max_digits=7)),
                ('close', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pre_close', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('p_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(max_length=10)),
            ],
        ),
    ]
