# Generated by Django 4.0.2 on 2022-02-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0009_stockme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksz',
            name='ma10',
        ),
        migrations.RemoveField(
            model_name='stocksz',
            name='ma20',
        ),
        migrations.RemoveField(
            model_name='stocksz',
            name='ma5',
        ),
        migrations.RemoveField(
            model_name='stocksz',
            name='v_ma10',
        ),
        migrations.RemoveField(
            model_name='stocksz',
            name='v_ma20',
        ),
        migrations.RemoveField(
            model_name='stocksz',
            name='v_ma5',
        ),
        migrations.RemoveField(
            model_name='stockszc',
            name='ma10',
        ),
        migrations.RemoveField(
            model_name='stockszc',
            name='ma20',
        ),
        migrations.RemoveField(
            model_name='stockszc',
            name='ma5',
        ),
        migrations.RemoveField(
            model_name='stockszc',
            name='v_ma10',
        ),
        migrations.RemoveField(
            model_name='stockszc',
            name='v_ma20',
        ),
        migrations.RemoveField(
            model_name='stockszc',
            name='v_ma5',
        ),
    ]
