# Generated by Django 4.0.2 on 2022-02-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0011_alter_stockbj_date_alter_stockme_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
