# Generated by Django 4.0.3 on 2022-03-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_views'),
        ('accounts', '0001_initial'),
        ('astocks', '0012_alter_stocklist_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_date', models.DateField(db_index=True, max_length=10)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('reasons', models.CharField(max_length=100, null=True)),
                ('short', models.CharField(max_length=100, null=True)),
                ('ndperformance', models.CharField(max_length=50, null=True)),
                ('tenday_limits', models.PositiveIntegerField(null=True)),
                ('summary', models.TextField(max_length=1000, null=True)),
                ('boards', models.ManyToManyField(related_name='stockchooses', to='boards.board')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockchooses', to='accounts.persons')),
            ],
        ),
    ]
