# Generated by Django 4.0.5 on 2023-01-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0013_stockchoose'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbj',
            name='volume_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocksh',
            name='volume_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockshk',
            name='volume_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocksz',
            name='volume_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockszc',
            name='volume_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
