# Generated by Django 4.0.5 on 2023-10-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_boardtype'),
        ('astocks', '0015_stocklimitup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LimitupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stocksector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=11)),
                ('open', models.DecimalField(decimal_places=2, max_digits=11)),
                ('high', models.DecimalField(decimal_places=2, max_digits=11)),
                ('close', models.DecimalField(decimal_places=2, max_digits=11)),
                ('pre_close', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=11)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=18)),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('volume_ratio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('limitup_number', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ('growth', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('growth_pre', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('growth_3', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('growth_20', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('growth_60', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Continuerise_days', models.DecimalField(decimal_places=0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('boards', models.ManyToManyField(related_name='stockses', to='boards.board')),
            ],
        ),
        migrations.AddField(
            model_name='stockchoose',
            name='types',
            field=models.ManyToManyField(related_name='stockchooses', to='astocks.choosetype'),
        ),
        migrations.AddField(
            model_name='stocklimitup',
            name='types',
            field=models.ManyToManyField(related_name='stocklimitups', to='astocks.limituptype'),
        ),
    ]
