# Generated by Django 4.0.5 on 2023-10-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0016_choosetype_limituptype_stocksector_stocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksector',
            name='date',
            field=models.DateField(db_index=True, max_length=10, null=True),
        ),
    ]
