# Generated by Django 4.0.5 on 2023-10-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0017_stocksector_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksector',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
