# Generated by Django 4.0.5 on 2023-10-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0018_stocksector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='growth',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
