# Generated by Django 4.0.5 on 2023-10-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0019_stocks_growth'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockchoose',
            name='growth',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocklimitup',
            name='growth',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
