# Generated by Django 4.0.5 on 2023-11-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0020_stockchoose_growth_stocklimitup_growth'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='blockname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
