# Generated by Django 4.0.5 on 2023-11-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0021_stocks_blockname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbj',
            name='capital_inflow',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocksh',
            name='capital_inflow',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockshk',
            name='capital_inflow',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocksz',
            name='capital_inflow',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockszc',
            name='capital_inflow',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
