# Generated by Django 4.0.5 on 2024-03-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0022_stockbj_capital_inflow_stocksh_capital_inflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockindex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=11)),
                ('name', models.CharField(db_index=True, max_length=50, null=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=11)),
                ('high', models.DecimalField(decimal_places=2, max_digits=11)),
                ('close', models.DecimalField(decimal_places=2, max_digits=11)),
                ('low', models.DecimalField(decimal_places=2, max_digits=11)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('growth', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amplitude', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(db_index=True, max_length=10, null=True)),
            ],
        ),
    ]
