# Generated by Django 4.0.5 on 2024-04-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0023_stockindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbj',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stocksector',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stocksh',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stockshk',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stocksz',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stockszc',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
