# Generated by Django 4.0.5 on 2024-04-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0024_stockbj_pe_stocksector_pe_stocksh_pe_stockshk_pe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbj',
            name='nf',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocksh',
            name='nf',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockshk',
            name='nf',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocksz',
            name='nf',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockszc',
            name='nf',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
