# Generated by Django 4.0.5 on 2024-04-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0025_stockbj_nf_stocksh_nf_stockshk_nf_stocksz_nf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbj',
            name='committee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockindex',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='stocksh',
            name='committee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockshk',
            name='committee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocksz',
            name='committee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockszc',
            name='committee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
