# Generated by Django 4.0.5 on 2024-04-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0026_stockbj_committee_stockindex_pe_stocksh_committee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='committee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
