# Generated by Django 4.0.5 on 2024-05-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0027_stocks_committee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksector',
            name='growth_20',
        ),
        migrations.RemoveField(
            model_name='stocksector',
            name='growth_60',
        ),
        migrations.AddField(
            model_name='stocksector',
            name='Continuerise_30_limitup',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='stocksector',
            name='growth_fall',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
