# Generated by Django 4.0.5 on 2025-01-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0028_remove_stocksector_growth_20_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksector',
            name='inflow',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
