# Generated by Django 4.0.5 on 2025-01-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0029_stocksector_inflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='inflow',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='nf',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
