# Generated by Django 4.0.5 on 2025-04-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0030_stocks_inflow_stocks_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='circulation_market_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='market_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
