# Generated by Django 4.0.5 on 2025-04-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0031_stocklist_circulation_market_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='circulation_market_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='market_value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
