# Generated by Django 4.0.5 on 2025-04-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0032_alter_stocklist_circulation_market_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='circulation_market_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='market_value',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
