# Generated by Django 4.0.5 on 2025-08-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0033_stocks_circulation_market_value_stocks_market_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexinflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=11)),
                ('name', models.CharField(db_index=True, max_length=50, null=True)),
                ('inf', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('outf', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('inflow', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateField(db_index=True, max_length=10, null=True)),
            ],
        ),
    ]
