# Generated by Django 4.0.5 on 2025-08-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astocks', '0034_indexinflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexinflow',
            name='growth',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
