# Generated by Django 4.0.5 on 2025-04-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='growth',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
